STATES_CONNECTIVITY = {
    "Alabama":              ["Mississippi", "Tennessee", "Florida", "Georgia"],
    "Alaska":               [],
    "Arizona":              ["Nevada", "New Mexico", "Utah", "California", "Colorado"],
    "Arkansas":             ["Oklahoma", "Tennessee", "Texas", "Louisiana", "Mississippi", "Missouri"],
    "California":           ["Oregon", "Arizona", "Nevada"],
    "Colorado":             ["New Mexico", "Oklahoma", "Utah", "Wyoming", "Arizona", "Kansas", "Nebraska"],
    "Connecticut":          ["New York", "Rhode Island", "Massachusetts"],
    "Delaware":             ["New Jersey", "Pennsylvania", "Maryland"],
    "District of Columbia": ["Maryland", "Virginia"],
    "Florida":              ["Georgia", "Alabama"],
    "Georgia":              ["North Carolina", "South Carolina", "Tennessee", "Alabama", "Florida"],
    "Hawaii":               [],
    "Idaho":                ["Utah", "Washington", "Wyoming", "Montana", "Nevada", "Oregon"],
    "Illinois":             ["Kentucky", "Missouri", "Wisconsin", "Indiana", "Iowa", "Michigan"],
    "Indiana":              ["Michigan", "Ohio", "Illinois", "Kentucky"],
    "Iowa":                 ["Nebraska", "South Dakota", "Wisconsin", "Illinois", "Minnesota", "Missouri"],
    "Kansas":               ["Nebraska", "Oklahoma", "Colorado", "Missouri"],
    "Kentucky":             ["Tennessee", "Virginia", "West Virginia", "Illinois", "Indiana", "Missouri", "Ohio"],
    "Louisiana":            ["Texas", "Arkansas", "Mississippi"],
    "Maine":                ["New Hampshire"],
    "Maryland":             ["Virginia", "West Virginia", "Delaware", "Pennsylvania"],
    "Massachusetts":        ["New York", "Rhode Island", "Vermont", "Connecticut", "New Hampshire"],
    "Michigan":             ["Ohio", "Wisconsin", "Illinois", "Indiana", "Minnesota"],
    "Minnesota":            ["North Dakota", "South Dakota", "Wisconsin", "Iowa", "Michigan"],
    "Mississippi":          ["Louisiana", "Tennessee", "Alabama", "Arkansas"],
    "Missouri":             ["Nebraska", "Oklahoma", "Tennessee", "Arkansas", "Illinois", "Iowa", "Kansas", "Kentucky"],
    "Montana":              ["South Dakota", "Wyoming", "Idaho", "North Dakota"],
    "Nebraska":             ["Missouri", "South Dakota", "Wyoming", "Colorado", "Iowa", "Kansas"],
    "Nevada":               ["Idaho", "Oregon", "Utah", "Arizona", "California"],
    "New Hampshire":        ["Vermont", "Maine", "Massachusetts"],
    "New Jersey":           ["Pennsylvania", "Delaware", "New York"],
    "New Mexico":           ["Oklahoma", "Texas", "Utah", "Arizona", "Colorado"],
    "New York":             ["Pennsylvania", "Rhode Island", "Vermont", "Connecticut", "Massachusetts", "New Jersey"],
    "North Carolina":       ["Tennessee", "Virginia", "Georgia", "South Carolina"],
    "North Dakota":         ["South Dakota", "Minnesota", "Montana"],
    "Ohio":                 ["Michigan", "Pennsylvania", "West Virginia", "Indiana", "Kentucky"],
    "Oklahoma":             ["Missouri", "New Mexico", "Texas", "Arkansas", "Colorado", "Kansas"],
    "Oregon":               ["Nevada", "Washington", "California", "Idaho"],
    "Pennsylvania":         ["New York", "Ohio", "West Virginia", "Delaware", "Maryland", "New Jersey"],
    "Rhode Island":         ["Massachusetts", "New York", "Connecticut"],
    "South Carolina":       ["North Carolina", "Georgia"],
    "South Dakota":         ["Nebraska", "North Dakota", "Wyoming", "Iowa", "Minnesota", "Montana"],
    "Tennessee":            ["Mississippi", "Missouri", "North Carolina", "Virginia", "Alabama", "Arkansas", "Georgia", "Kentucky"],
    "Texas":                ["New Mexico", "Oklahoma", "Arkansas", "Louisiana"],
    "Utah":                 ["Nevada", "New Mexico", "Wyoming", "Arizona", "Colorado", "Idaho"],
    "Vermont":              ["New Hampshire", "New York", "Massachusetts"],
    "Virginia":             ["North Carolina", "Tennessee", "West Virginia", "Kentucky", "Maryland"],
    "Washington":           ["Oregon", "Idaho"],
    "West Virginia":        ["Pennsylvania", "Virginia","Kentucky", "Maryland", "Ohio"],
    "Wisconsin":            ["Michigan", "Minnesota", "Illinois", "Iowa"],
    "Wyoming":              ["Nebraska", "South Dakota", "Utah", "Colorado", "Idaho", "Montana"]
}

STATE_TO_ABBR = {
    "Alabama": "AL",
    "Kentucky": "KY",
    "Ohio": "OH",
    "Alaska": "AK",
    "Louisiana": "LA",
    "Oklahoma": "OK",
    "Arizona": "AZ",
    "Maine": "ME",
    "Oregon": "OR",
    "Arkansas": "AR",
    "Maryland": "MD",
    "Pennsylvania": "PA",
    "American Samoa": "AS",
    "Massachusetts": "MA",
    "Puerto Rico": "PR",
    "California": "CA",
    "Michigan": "MI",
    "Rhode Island": "RI",
    "Colorado": "CO",
    "Minnesota": "MN",
    "South Carolina": "SC",
    "Connecticut": "CT",
    "Mississippi": "MS",
    "South Dakota": "SD",
    "Delaware": "DE",
    "Missouri": "MO",
    "Tennessee": "TN",
    "District of Columbia": "DC",
    "Montana": "MT",
    "Texas": "TX",
    "Florida": "FL",
    "Nebraska": "NE",
    "Trust Territories": "TT",
    "Georgia": "GA",
    "Nevada": "NV",
    "Utah": "UT",
    "Guam": "GU",
    "New Hampshire": "NH",
    "Vermont": "VT",
    "Hawaii": "HI",
    "New Jersey": "NJ",
    "Virginia": "VA",
    "Idaho": "ID",
    "New Mexico": "NM",
    "Virgin Islands": "VI",
    "Illinois": "IL",
    "New York": "NY",
    "Washington": "WA",
    "Indiana": "IN",
    "North Carolina": "NC",
    "West Virginia": "WV",
    "Iowa": "IA",
    "North Dakota": "ND",
    "Wisconsin": "WI",
    "Kansas": "KS",
    "Northern Mariana Islands": "CM",
    "Wyoming": "WY"
}

ABBR_TO_STATE = {y:x for x,y in STATE_TO_ABBR.items()}
